import java.util.HashMap;
import java.util.Map;

/**Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.
 * Created by nagen on 10/6/16.
 */
public class FindTheDifference {
    public static void main(String[] args) {
        FindTheDifference fd = new FindTheDifference();
        System.out.println(fd.findTheDifference("abcde","abcdef"));
        System.out.println(fd.findDifference("abcde","fabcde"));
    }

    private char findDifference(String s, String t){
        int n = t.length();
        char c = t.charAt(n - 1);
        for (int i = 0; i < n - 1; ++i) {
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }

    private char findTheDifference(String s, String t) {
        HashMap<Character, Integer> map = new HashMap<>();
        for (char c : t.toCharArray()) {
            if (map.containsKey(c)) {
                map.put(c, map.get(c) + 1);
            } else {
                map.put(c, 1);
            }
        }

        for (char c : s.toCharArray()) {
            if (map.containsKey(c)) {
                map.put(c, map.get(c) - 1);
            }
        }

        for (Object o : map.entrySet()) {
            Map.Entry pair = (Map.Entry) o;
            if (Integer.parseInt(pair.getValue().toString()) == 1)
                return (char) pair.getKey();

        }

        return (char) -1;
    }
}
